### PR TITLE
fixing images in manual, also minor text truncations

### PR DESCRIPTION
**Pull request by Badnoob-327**
updating

### CODE REVIEW

**Comment by timmit99** [comment]
image
@Badnoob-327 still looks like the Right Magnet Holder image is broken

Also, these are pixelated for some reason:
image

middle support removal photo is pixelated:
image

**Comment by 0x3333** [comment]
There is still some issues:

image

**Comment by Badnoob-327** [comment]
> image @Badnoob-327 still looks like the Right Magnet Holder image is broken
> 
> Also, these are pixelated for some reason: image
> 
> middle support removal photo is pixelated: image

fixed...with the smaller images, theres a balance between low contrast and low dpi, I adjusted them as best I can

**Comment by Badnoob-327** [comment]
> There are still some issues:
> 
> image

fixed, thank you!

**Review by nemgrea — APPROVED** [review]

**Pull request merged**
