### PR TITLE
Add image citation.

### PR DESCRIPTION
**Pull request by KiloQubit**

### CODE REVIEW

**Comment by KiloQubit** [comment]
@MapleLeafMakers please review

**Comment by Badnoob-327** [comment]
should "image" be capitalized?  
is "image" correct (technically its a GIF...)?
(I don't really know myself)

link appears correct

**Comment by MapleLeafMakers** [comment]
Looks great, thank you very much!

**Comment by KiloQubit** [comment]
@Badnoob-327 how's this for terminology change?

**Review by Badnoob-327 — APPROVED** [review]

**Pull request merged**
